# Generated by Django 5.2 on 2025-04-06 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RubbishType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("street", models.TextField()),
                ("city", models.TextField()),
                ("postcode", models.TextField()),
                ("council", models.TextField()),
            ],
            options={
                "db_table": "app_version",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("street", "city", "postcode"), name="unique_street_city_postcode"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CollectionSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "frequency",
                    models.CharField(choices=[("W", "Weekly"), ("B", "Bi-Weekly")], max_length=1),
                ),
                ("start_date", models.DateField()),
                ("import_date", models.DateField()),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rubbish_collection.address",
                    ),
                ),
                (
                    "rubbish_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="rubbish_collection.rubbishtype",
                    ),
                ),
            ],
        ),
    ]
